[package]
name = "binserde"
version = "0.1.1"
authors = ["soruh <mail@soruh.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
unstable = []
default = []

[dependencies]


[dev-dependencies]
rand = "0.7.3"


